language: python

python:
- '2.7'

sudo: required

services:
- docker

notifications:
  email:
    recipients:
    - umaganapathyswork@gmail.com
    on_success: never
    on_failure: always

env:
  global:
    secure: QXB1gwpxPy6zfsP6s85MgO7L7kmBan9tgwGA8PuqkgqlzPt2H6OfB1VihicQFfSxRqLgU+5xaZqdsnGJwV5kLvYYyLG88K4DrvTo/h81vXJPqBgF4WS6FcvmGu+TWTuKfQ+yS0uZyJYyT3yESXDUB6EkvI2SDpTFMNdQcKh6k4HMpr+N9oHQJUbwsP8n1P64evAc90zEz9+qGAbNcaPPjqLy9HyUTlvlB9oOnHxwEqw9721fCctWJRIxDBdl8NLhywthZz2LvQr9mIPewPdLljltx9jiuEHcCHRiCIqPpGe6roa4sdwDjD3BP6gdFS0i9GM84EOBjwsVOGnyvsKBCEzThBIjX7otA8bE9IIWfNw7Z9pWZkTPcYP/dhppm5srwJUx0eKJAoztozsew1akZsmwa6XfCPvxK5br9xDKggiJWkXEGw49oIi+GZ/5SFdhOJQPTxYHEdFMeDH6fLE55dA8b+udrkCIQWht+mdOQBe6NeESB9I97mmMoqoOyhy9HPoQgyLhyNNRKZbNBaIiZUtlr7W7kXrJsXmFbPtjmGemYi8xFpC5020DDjI18GmQQxqXeJYnjmzbyKU+6D2DwRsjnVZfW5ErDhsNpJ9UqIxiIJxL05tTtzD9vWGzwQIZN6o/sSCY4o7gY5bFMrYcp6kXfPvLRRxZOev7CHJR0Cg=

branches:
  only:
  - master

before_install:
- docker version
- python --version
- javac -version
- java -version

install:
- pip install coveralls
- git clone https://github.com/kbase/jars
- git clone https://github.com/kbase/kb_sdk
- cd kb_sdk
- make
- make sdkbase
- docker images
- export PATH=$(pwd)/bin:$PATH
- cd ../
- git clone https://github.com/ugswork/ExpressionUtils.git
- cd ExpressionUtils
- kb-sdk test || true
- sed -i "s/test_token=/test_token=$TEST_TOKEN/" test_local/test.cfg
- sed -i 's\https://appdev.kbase.us/services\https://ci.kbase.us/services\' test_local/test.cfg
- sed -i 's\https://appdev.kbase.us/services/auth/api/legacy/KBase/Sessions/Login\https://ci.kbase.us/services/auth/api/legacy/KBase/Sessions/Login\'
  test_local/test.cfg
- sed -i 's/$(id -u)/0:0/' test_local/run_tests.sh
- pwd=$(pwd)
- echo "#!/bin/bash" >> test_local/run_subjob.sh
- echo -e "$pwd/test_local/run_docker.sh run --rm --user 0:0 -v $pwd/test_local/subjobs/\$1/workdir:/kb/module/work
  -v $pwd/test_local/workdir/tmp:/kb/module/work/tmp \$4 -e \"SDK_CALLBACK_URL=\$3\"
  \$2 async" >> test_local/run_subjob.sh
- cat test_local/run_subjob.sh

script:
- kb-sdk test

after_success:
- cp test_local/workdir/.coverage .
- sudo mkdir -p /kb/module/lib/
- sudo cp -R test_local/workdir/kb/module/lib/ExpressionUtils /kb/module/lib/
- pwd
- ls -l /kb/module/lib/ExpressionUtils
- cat .coverage
- coverage report -m
- coveralls

